// !-- Do Not Hand Edit - This File is generated by CMAKE --!

#ifndef CONFIG_H
#define CONFIG_H 1

#define UFEAPI_DIR   "/home/yordan/Workspace/BabyMIND_FEB/libufe-apicpp"

/* #undef ROOT_FOUND */

/* #undef CLHEP_FOUND */


#endif // CONFIG_H
